[package]
name = "sphere"
version = "0.1.0"
authors = ["Yann Simon <yann.simon.fr@gmail.com>"]

[dependencies]
clap = "2.5"
hyper = "0.9"
rustc-serialize = "0.3"
chrono = "0.2"
log = "^0.3"
env_logger = "^0.3"
